server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://admin:adminpassword@localhost:27017/order?authSource=admin
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: Order

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
 
